name: Test Inflammation

on: push

jobs:
    build:
        strategy:
            matrix:
                os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
                python: ['3.11', '3.10', '3.9']
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python }}
            
            - name: Install Python Module
              run: python -m pip install -e .
            
            - name: Run Tests
              run: python -m pytest --cov=inflammation
            